#!/usr/bin/env python
import sys
import subprocess
import re

search = sys.argv[1]

#process = subprocess.Popen(['lpass','ls'], stdout=subprocess.PIPE)
process = subprocess.Popen(['lpass', 'show', '--basic-regexp', search], stdout=subprocess.PIPE)
stdout, stderr = process.communicate()
items = stdout.split("\n")

#matching_list = [s for s in items if search in s]

for item in items:
    match = re.search("id:\s(.*)]", item)
    if match :
        id = match.groups(0)[0]
        process = subprocess.Popen(['lpass','show',id], stdout=subprocess.PIPE)
        stdout, stderr = process.communicate()
        print stdout

